### ISSUE TITLE
CSS injected inside <script> tags in Safari

### ISSUE THREAD

**Issue by bakerkretzmar** [jhabdas/fetch-inject#19] opened 2017-05-05 02:41 UTC
Hey, I think this a bug? I'm new to this so please bear with me if it's a stupid question or I'm missing something really obvious!

I'm using fetch-inject in a tiny Jekyll site with just a few assets, mostly to play around and get more comfortable with stuff like this. Everything's working perfectly... in Chrome. In Safari, the contents of the css files I'm trying to inject are being placed inside `<script>` tags rather than `<style>` tags. I'm using Safari 10.1 on macOS Sierra. This is the site: [https://mghamilton.ca](https://mghamilton.ca).

If I run fetchInject in the console, in Chrome it works fine and the blob I get back has a `type` of `text/css`, whereas in Safari it injects the css inside `<script>` tags and the blob comes back with the `type` empty. Is this maybe related to #18?

<img width="1013" alt="screen shot 2017-05-04 at 11 30 18 pm" src="https://cloud.githubusercontent.com/assets/18192441/25732083/4438df4e-3122-11e7-9428-962e917bacab.png">

<img width="949" alt="screen shot 2017-05-04 at 11 31 05 pm" src="https://cloud.githubusercontent.com/assets/18192441/25732085/4add8dae-3122-11e7-8af5-01713ac64486.png">

**Comment by jhabdas** [comment] 2017-05-05 15:59
Thanks for the issue. Sounds like your doing everything right and there may be a bug in the WebKit implementation of the Fetch API Last I spoke with Apple about Fetch API this is what I was told:

> Fetch will become available in Safari in the Safari 10.1 release that ships with macOS Sierra 10.12.4 and Safari on iOS 10.3. Jon Davis,  Web Technologies Evangelist

Could you provide your version info so we can look at opening a bug for WebKit?

**Comment by bakerkretzmar** [comment] 2017-05-05 17:08
For sure, I'm using macOS Sierra 10.12.4 (16E195) and Safari 10.1 (12603.1.30.0.34). When I got it working I was in Chrome 57.0.2987.133. I haven't tested it on a phone at all yet.

**Comment by bjoe2k4** [comment] 2017-05-05 21:41
fwiw, FF v53 is broken, too. @bakerkretzmar i would try an earlier version prior to #18 to investigate further on this issue.

**Comment by bakerkretzmar** [comment] 2017-05-06 00:14
Thanks for pointing that out, Firefox is doing something different but also weird. Messing around in the console it looks like in FF the promise never returns anything, trying to run `fetchInject` manually it just sits there "pending" forever.

@bjoe2k4 I tried fetch-inject v1.6.10 instead, before `type` was removed in #18, and this changed a couple of details but it didn't fix my problem. It added the `type` attribute back into the element being injected, but the element itself was still `<script>` and not `<style>`.

In Chrome everything worked, it injected the css with a `<style type="text/css">` tag as expected:

<img width="301" alt="screen shot 2017-05-05 at 8 38 45 pm" src="https://cloud.githubusercontent.com/assets/18192441/25767809/0775d092-31d3-11e7-8a02-81096810b73d.png">

In Safari it injected `<script type>`, and in the console I'm still getting back a blob with an empty `type`:

<img width="646" alt="screen shot 2017-05-05 at 8 32 07 pm" src="https://cloud.githubusercontent.com/assets/18192441/25767846/6528c136-31d3-11e7-899b-cf2774a278a8.png">

Safari also immediately gives me these errors in the console (line 12 is where I have the fetch-inject script, there is nothing at 1:232):

<img width="401" alt="screen shot 2017-05-05 at 8 53 08 pm" src="https://cloud.githubusercontent.com/assets/18192441/25767991/fe5ca542-31d4-11e7-9d83-d966a275ca1b.png">

In Firefox it injected `<script type="text/css; charset=utf-8">`. I don't know where the `charset` bit came from, or the rest of it for that matter since I can't get it to give me back a blob at all.

<img width="574" alt="screen shot 2017-05-05 at 8 34 26 pm" src="https://cloud.githubusercontent.com/assets/18192441/25767908/0696a84e-31d4-11e7-9ca4-d5a96a855567.png">

Idk if this means anything, but looking inside the `fetchInject()` method on the window object in FF seems to just be endless constructors.

<img width="315" alt="screen shot 2017-05-05 at 8 46 04 pm" src="https://cloud.githubusercontent.com/assets/18192441/25768044/9947debe-31d5-11e7-8d80-3a521fccb09e.png">

I tried this in Firefox 53.0.2 and also Developer, 54.0a2 (2017-05-05).


It seems like the real problem here is the blob coming back with an empty `type` (or not coming back at all in FF). Does that point to something wrong with the `fetch` response?

**Comment by bjoe2k4** [comment] 2017-05-06 00:22
You may try my personal fork (https://github.com/bjoe2k4/fetch-inject) fixing at least the charset problem ( which may be the root cause of all your troubles). This additional charset header is sent by your webserver.

Some further discussion can be found here #14

**Comment by jhabdas** [comment] 2017-05-06 00:29
I'm erasing this info. Because this is going off course. I'm debugging the problem now. @bjoe2k4 please buzz off.

**Comment by jhabdas** [comment] 2017-05-06 00:38
Thanks for the additional info. This is a great example of a reduced test case. I'm running the same builds of Sierra and Safari and see the following when I run the standard fetch:

```
fetch('https://mghamilton.ca/assets/main-b6e362c07a788ca2f79b5f7435c149392ccccc38a6726f97a8e30b7e03b02ec6.css').then(res => { console.dir(res.blob()) })
```

<img width="580" alt="screen shot 2017-05-06 at 8 33 08 am" src="https://cloud.githubusercontent.com/assets/440298/25768438/adfd4c3e-3236-11e7-8c29-f399ea31972b.png">

Here we can see Safari is not setting `type` in the response `blob`. So I checked the response headers using cURL statement with the verbose flag outputting to a file:

```
curl -vO 'https://mghamilton.ca/assets/main-b6e362c07a788ca2f79b5f7435c149392ccccc38a6726f97a8e30b7e03b02ec6.css'
```

<img width="818" alt="screen shot 2017-05-06 at 8 37 08 am" src="https://cloud.githubusercontent.com/assets/440298/25768462/3a835a2c-3237-11e7-9537-59509a2a7f33.png">

We can see the response headers contain the proper content type of `text/css` (highlighted in the above image).

Next step is to determine why the `type` attribute is not set in the response blob.

**Comment by jhabdas** [comment] 2017-05-06 01:58
Here is the reduced test case: https://bl.ocks.org/jhabdas/a1d845adb7c93d80c8d81da0687c2c7e

**Comment by jhabdas** [comment] 2017-05-06 02:15
And here is the bug: https://bugs.webkit.org/show_bug.cgi?id=170849

**Comment by jhabdas** [comment] 2017-05-06 02:20
@bakerkretzmar Given the bug is already being patched, I expect it to be fixed soon on in the nightly. Thanks for the report. I will leave this issue open until the fix lands in Safari for both desktop and iOS.

For additional information on WebKit status of HTML features please see https://webkit.org/status/

Regards,
Josh

**Comment by bakerkretzmar** [comment] 2017-05-06 15:37
Cool, thanks so much for doing this! I looked through webkit's bug tracker earlier but didn't find that one.

I tried using a cURL to grab one of the javascript files and it returns `Content-Type: application/javascript` as expected—any idea why the css files come back with `charset=utf-8` in the `type` field too? Does that matter?

**Comment by jhabdas** [comment] 2017-05-06 17:08
> Does that matter?

Not in the way Fetch Inject uses them. If you ever want to grab parts of the full content type header you can do so by accessing "headers" prop in the fetch response, though there's not a need to use it yet for Fetch Inject, which is small and focused, and plans to expand next to font loading.

And though we don't use it explicitly, if you're curious about HTTP content type header you can learn more about it here:

https://tools.ietf.org/html/rfc2045#section-5.1

And see what real life examples look like here:

* http://www.iana.org/assignments/media-types/media-types.xhtml
* http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
* http://hg.nginx.org/nginx/raw-file/default/conf/mime.types

And even register your own custom MIME types and [serve them up with Hugo](https://github.com/bep/hugo/blob/custom-output/docs/content/extras/custom-output-types.md) if you wanted to get creative. Have fun!

**Comment by jhabdas** [comment] 2017-05-07 05:42
@bakerkretzmar FYI, just opened #20. When you find an issue, just open a new issue for triage so we can track it and help keep the repo in order.

**Comment by jhabdas** [comment] 2017-05-09 09:46
This has been resolved in the Nightly build and Safari is now returning the expected value of `text/css` for the reduced test case. I said I'd keep this open until it landed in the production browsers. But that would require work so I'm closing this. It's fixed with no action required.

**Closed by jhabdas** 2017-05-09 09:46 UTC
Labels: wontfix
